config/routes.rb
Rails.application.routes.draw do
  devise_for :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.permision == "admin"
      can :manage, :all
    elsif user.permision == "manager"
      can [:read, :update], [Category, Book, Author, Publisher, RequestBook]
      cannot [:update, :create, :destroy], User
      can [:read, :update], User,  id: user.id
      comment_permission user
    else
      can [:read, :update], User,  id: user.id
      comment_permission user
    end
  end

  def comment_permission user
    can :create, Review
    can :update, Review, user_id: user.id
    can :destroy, Review, user_id: user.id
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :authorBooks
  has_many :relationships, as: :following
end

app/models/author_book.rb
class AuthorBook < ApplicationRecord
  belongs_to :author
  belongs_to :book
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :publisher
  has_many :categoryBooks
  has_many :authorBooks
  has_many :reviews
  has_many :likes
  has_many :rates
  has_many :requestBooks
  has_many :relationships, as: :following
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :categoryBooks
end

app/models/category_book.rb
class CategoryBook < ApplicationRecord
  belongs_to :book
  belongs_to :category
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/publisher.rb
class Publisher < ApplicationRecord
  has_many :books
end

app/models/rate.rb
class Rate < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :following, polymorphic: true
end

app/models/relationship_user.rb
class RelationshipUser < ApplicationRecord
  belongs_to :follower, class_name: User.name
  belongs_to :followed, class_name: User.name

  validates :follower, presence: true
  validates :followed, presence: true
end

app/models/request_book.rb
class RequestBook < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable
  has_many :reviews
  has_many :likes
  has_many :rates
  has_many :requestBooks
  has_many :relationships, as: :following
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :load_user, except: %i(new index create)
  load_and_authorize_resource

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).user_order.page(params[:page]).
      per Settings.user.user_number
    @allUser = User.all
    respond_to do |format|
      format.html
      format.csv {send_data @allUser.to_csv}
      format.xls {send_data @allUser.to_csv(col_sep: "\t")}
    end
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params

    if @user.save
      flash[:success] = t ".create_user_success"
      redirect_to admin_users_path
    else
      flash.now[:error] = t ".create_user_fail"
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params_update_password) && @user.password
      flash[:success] = "Update password success!"
      redirect_to admin_users_path
    elsif @user.update_attributes user_params_edit_not_password
      flash[:success] = t ".success"
      redirect_to admin_users_path
    else
      flash.now[:danger] = t ".fail"
      render :edit
    end
  end

  def destroy
    if @user.destroy
      flash.now[:success] = t ".delete_success"
      respond_to do |format|
        format.html {
          redirect_to admin_users_path
        }
        format.js
      end
    else
      flash.now[:danger] = t ".delete_failed"
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation, :permision
  end

  def user_params_edit_not_password
    params.require(:user).permit :name, :email, :permision
  end

  def user_params_update_password
    params.require(:user).permit :password,
      :password_confirmation
  end

  def load_user
    @user = User.find_by id: params[:id]

    render file: "public/404.html", layout: false unless @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: %i(index new)
  before_action :request_book_accept, :request_book_pending, only: :show

  def index
    @q = User.ransack(params[:q])
    @users = @q.result(distinct: true).user_order.page(params[:page]).
      per Settings.book.number_book_page
  end

  def show
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params_update_password) && @user.password
      flash[:success] = t ".success_password"
      redirect_to user_path @user
    elsif @user.update_attributes user_params_edit_not_password
      flash[:success] = t ".success"
      redirect_to user_path @user
    else
      flash.now[:danger] = t ".fail"
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit :name, :password,
      :password_confirmation, :phone, :avatar
  end

  def user_params_edit_not_password
    params.require(:user).permit :name, :phone, :avatar
  end

  def user_params_update_password
    params.require(:user).permit :password,
      :password_confirmation
  end

  def request_book_pending
    @request_book_pendings = RequestBook.where(user_id: params[:id], status: "pending")
  end

  def request_book_accept
    @request_book_accepts = RequestBook.where(user_id: params[:id], status: "accept")
  end

  def load_user
    @user = User.find_by id: params[:id]

    render file: "public/404.html", layout: false unless @user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?
    messages = resource.errors.full_messages.map{|message| content_tag(:li, message)}.join
    html = <<-HTML
      <script type="text/javascript">
        toastr.error('#{messages}');
      </script>
    HTML
    html.html_safe
  end

  def picture_for user
    if user.avatar?
      image_tag user.avatar_url()
    else
      image_tag "default.png.jpg"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/admin/users/_form.html.erb
<%= form_for [:admin, @user], :html => {:class => "form-valide"} do |f| %>
  <%= error_messages @user %>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :name %>
    </div>
    <div class="col-md-8">
    <%= f.text_field :name, class: "form-control",
      placeholder: "Enter a username.." %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :email %><span class="text-danger">*</span>
    </div>
    <div class="col-md-8">
    <%= f.email_field :email, class: "form-control",
      placeholder: "Enter a email.." %>
    </div>
  </div>
  <% unless yield(:button) == "Edit" %>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :password %><span class="text-danger">*</span>
    </div>
    <div class="col-md-8">
    <%= f.password_field :password, class: "form-control",
      placeholder: "Enter a password.." %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :password_confirmation %><span class="text-danger">*</span>
    </div>
    <div class="col-md-8">
      <%= f.password_field :password_confirmation, autocomplete: "off",
        class: "form-control", placeholder: "Enter password confirmation" %>
    </div>
  </div>
  <% end %>
  <div class="form-group row">
    <label class="col-lg-3 col-form-label" for="val-skill">Permission </label>
    <div class="col-lg-8">
      <%= f.select(:permision, options_for_select(["admin", "manager", "user"], :selected => f.object.permision),{include_blank: true}, {:class => "form-control"}) %>
    </div>
  </div>
  <div class="actions form-group">
      <%= f.submit yield(:button), class: "btn btn-primary" %>
  </div>
<% end %>

<% if yield(:button) == "Edit" %>
<h2><%= t ".update_password" %></h2>
<%= form_for [:admin, @user], :html => {:class => "form-valide-2"} do |f| %>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :password %><span class="text-danger">*</span>
    </div>
    <div class="col-md-8">
    <%= f.password_field :password, class: "form-control",
      placeholder: "Enter a password.." %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :password_confirmation %><span class="text-danger">*</span>
    </div>
    <div class="col-md-8">
      <%= f.password_field :password_confirmation, autocomplete: "off",
        class: "form-control", placeholder: "Enter password confirmation" %>
    </div>
  </div>
  <div class="actions form-group">
      <%= f.submit t(".update_password"), class: "btn btn-primary" %>
  </div>
<% end %>
<% end %>

app/views/admin/users/destroy.js.erb
$('#user-<%= @user.id %>').remove();

app/views/admin/users/edit.html.erb
<% provide :title, t(".edit_user") %>
<% provide :button, t(".edit") %>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="card">
        <div class="card-body">
          <div class="form-validation">
            <%= render "form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t(".list_user") %>
<div class="col-12">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title"><%= t ".date_export" %></h4>
        <div class="table-responsive m-t-40">
          <div id="example23_wrapper" class="dataTables_wrapper">
            <div class="dt-buttons">
              <span><%= link_to t(".csv"), admin_users_path(format: "csv"),
                class: "dt-button buttons-pdf buttons-html5" %></span>
              <span><%= link_to t(".excel"), admin_users_path(format: "xls"),
                class: "dt-button buttons-pdf buttons-html5" %></span>
              </a>
            </div>
          <div id="example23_filter" class="dataTables_filter">
            <%= search_form_for @q, url: admin_users_path do |f| %>
              <%= f.label :name %>
              <%= f.search_field :name_cont %>

              <%= f.label :email %>
              <%= f.search_field :email_cont %>

              <%= f.label :permission %>
              <%= f.select :permision_cont,
                options_for_select({"admin" => "1", "manager" => "2", "user" => "0"}), {include_blank: ""} %>
              <%= f.submit %>
            <% end %>
          </div>
          <%= paginate @users %>
          <table class="display nowrap table table-hover table-striped table-bordered dataTable">
            <thead>
              <tr role="row">
                <th><%= t ".name" %></th>
                <th><%= t ".email" %></th>
                <th><%= t ".permission" %></th>
                <th><%= t ".edit_delete" %></th>
            </thead>
            <tbody>
              <% @users.each do |user| %>
                <tr role="row" class="odd" id="user-<%= user.id %>" >
                  <td><%= user.name %></td>
                  <td><%= user.email %></td>
                  <td><%= user.permision %></td>
                  <td class="edit_destroy">
                    <% if current_user.permision == "admin" %>
                      <%= link_to edit_admin_user_path user do %>
                        <i class="fa fa-pencil" aria-hidden="true"></i>
                      <% end %>
                    <% end %>
                    <% if can? :destroy, user %>
                      <%= link_to admin_user_path(user), method: :delete, remote: true, data:{confirm: t(".sure")} do %>
                        <i class="fa fa-trash-o" aria-hidden="true"></i>
                      <% end %>
                    <% end %>
                    </td>
                  </td>
                </tr>
              <% end %>
            </tbody>
            </table>
          <%= paginate @users %>
        </div>
    </div>
  </div>
</div>

app/views/admin/users/new.html.erb
<% provide :title, t(".create_user") %>
<% provide :button, t(".create") %>
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-10">
      <div class="card">
        <div class="card-body">
          <div class="form-validation">
            <%= render "form" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>

  <div><%= hidden_field_tag :followed_id, @user.id %></div>

  <%= f.submit t(".follow"), class: "btn-1 sm shadow-0" %>
<% end %>

app/views/users/_form.html.erb
<h2><%= t ".update_profile" %></h2>
<%= form_for @user, :html => {:class => "form-valide"} do |f| %>
  <%= error_messages @user %>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :name %>
    </div>
    <div class="col-md-8">
    <%= f.text_field :name, class: "form-control",
      placeholder: "Enter a username.." %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :phone %>
    </div>
    <div class="col-md-8">
    <%= f.text_field :phone, class: "form-control",
      placeholder: "Enter phone.." %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :avatar %>
    </div>
    <div class="col-md-8">
      <%= f.file_field :avatar %>
    </div>
  </div>
  <div class="actions form-group">
      <%= f.submit t(".edit"), class: "btn btn-primary" %>
  </div>
<% end %>

<h2><%= t ".update_password" %></h2>
<%= form_for [:admin, @user], :html => {:class => "form-valide-2"} do |f| %>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :password %>
    </div>
    <div class="col-md-8">
    <%= f.password_field :password, class: "form-control",
      placeholder: "Enter a password.." %>
    </div>
  </div>
  <div class="field form-group row">
    <div class="col-lg-3 col-form-label">
      <%= f.label :password_confirmation %>
    </div>
    <div class="col-md-8">
      <%= f.password_field :password_confirmation, autocomplete: "off",
        class: "form-control", placeholder: "Enter password confirmation" %>
    </div>
  </div>
  <div class="actions form-group">
      <%= f.submit t(".update_password"), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
 html: {method: :delete}, remote: true) do |f| %>

  <%= f.submit t(".unfollow"), class: "btn-1 sm shadow-0" %>
<% end %>

app/views/users/edit.html.erb
<%= render "layouts/banner" %>
<div class="single-aurthor-detail tc-padding">
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= render "form" %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= render "layouts/banner" %>
<div class="product-grid-holder tc-padding">
  <div class="search-custom">
  <%= search_form_for @q, :class=>"navbar-form navbar-right" do |f| %>
    <%= f.label "Search" %>
    <%= f.search_field :name_or_email_cont,
      :class=>"form-control" %>
    <%= f.submit "search", :class=>"form-control" %>
  <% end %>
  </div>
<div class="author-listing tc-padding">
  <div class="container">
    <div class="row">
      <div class="col-lg-9 col-md-8 col-xs-12">
        <ul class="author-list">
          <% @users.each do |user| %>
            <li>
              <div class="author-list-widget">
                <div class="arthor-list-img">
                  <% if user.avatar.present? %>
                    <%= image_tag user.avatar.to_s %>
                  <% elsif %>
                    <%= image_tag "gray.png" %>
                  <% end %>
                  <div class="overlay">
                    <%= link_to "+", user_path(user), :class=>"position-center-center" %>
                  </div>
                </div>
                <div class="author-list-detail">
                  <h2><%= user.name %></h2>
                  <p><%= t ".email" %><%= user.email %></p>
                  <%= link_to user_path(user), :class => "btn-1 sm" do %>
                    <%= t ".read_more" %><i class="fa fa-arrow-circle-right"></i>
                  <% end %>
                </div>
              </div>
            </li>
          <% end %>
        </ul>
        <%= paginate @users %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<%= render "layouts/banner" %>
<div class="single-aurthor-detail tc-padding">
  <div class="container">
    <div class="row">
      <aside class="col-lg-4 col-md-5">
        <div class="arthor-detail-column">
          <div class="arthor-img">
            <% if @user.avatar.present? %>
              <%= image_tag @user.avatar.to_s %>
            <% elsif %>
              <%= image_tag "gray.png" %>
            <% end %>
            <% if can? :update, @user %>
              <%= link_to edit_user_path(@user), :class => "edit-tag" do %>
                <i class="fa fa-pencil-square-o"></i><%= t ".edit_profile" %>
              <% end %>
            <% end %>
          </div>
          <div class="arthor-detail">
            <h2>
              <% if @user.name.present? %>
                <%= @user.name %>
              <% else  %>
                <%= @user.email.split("@").first %>
              <% end %>
            </h2>
            <span><%= t ".email" %><%= @user.email %></span>
          </div>
          <div class="social-activity">
            <ul class="comments-status">
              <li><i class=""></i></li>
              <li><i class="fa fa-user-o"></i><%= t ".userfollow" %>
              <div class="followers"><%= @user.followers.size %></div></li>
              <li><i class=""></i></li>
            </ul>
            <% unless current_user == @user %>
              <div id="follow_form">
              <% if current_user.following?(@user) %>
                <%= render "unfollow" %>
              <% else %>
                <%= render "follow" %>
              <% end %>
              </div>
            <% end %>
          </div>
        </div>
      </aside>
      <div class="col-lg-8 col-md-7">
        <div class="single-arthor-detail">
          <div class="single-arthor-widget">
              <div class="single-arthor-widget">
                <h5><%= t ".recommended" %> </h5>
                <div class="filter-tags-holder">
                  <ul id="filterbale-nav" class="option-set">
                    <li><a class="selected" data-filter="*" href="">All Book</a></li>
                    <li><a data-filter=".most-recent" href="">Request_Book</a></li>
                    <li><a data-filter=".most-popular" href="">Books Borrowed</a></li>
                    <li><a data-filter=".follower" href="">Follower</a></li>
                    <li><a data-filter=".following" href="">Following</a></li>
                  </ul>
                </div>
                  <div id="filter-masonry" class="gallery-masonry">
                    <% if @request_book_pendings %>
                      <% @request_book_pendings.each do |request_book| %>
                        <div class="col-lg-3 col-xs-6 r-full-width masonry-grid most-recent">
                          <div class="recommended-book">
                            <div class="recommended-book-img">
                            <% if request_book.book.image_url.present? %>
                              <%= image_tag request_book.book.image_url %>
                            <% elsif %>
                              <%= image_tag "gray.png" %>
                            <% end %>
                            </div>
                          <div class="recommended-book-detail">
                              <h6><%= link_to request_book.book.name, book_path(request_book.book) %></h6>
                              <span> <% request_book.book.authors.each do |author| %>
                                <b><%= author.name %></b>
                              <% end %></span>
                              <ul class="rating-stars">
                                <div class="average-review-rating" data-score=<%= request_book.book.reviews.average(:rating) %>></div>
                              </ul>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                    <% if @request_book_accepts %>
                      <% @request_book_accepts.each do |request_book| %>
                        <div class="col-lg-3 col-xs-6 r-full-width masonry-grid most-popular">
                          <div class="recommended-book">
                            <div class="recommended-book-img">
                            <% if request_book.book.image_url.present? %>
                              <%= image_tag request_book.book.image_url %>
                            <% elsif %>
                              <%= image_tag "gray.png" %>
                            <% end %>
                            </div>
                          <div class="recommended-book-detail">
                              <h6><%= link_to request_book.book.name, book_path(request_book.book) %></h6>
                              <span> <% request_book.book.authors.each do |author| %>
                                <b><%= author.name %></b>
                              <% end %></span>
                              <ul class="rating-stars">
                                <div class="average-review-rating" data-score=<%= request_book.book.reviews.average(:rating) %>>
                              </ul>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                    <% if @user.followers %>
                      <% @user.followers.each do |follower| %>
                        <div class="col-lg-3 col-xs-6 r-full-width masonry-grid follower">
                          <div class="recommended-book">
                            <div class="recommended-book-img">
                            <% if follower.avatar.present? %>
                              <%= image_tag follower.avatar %>
                            <% elsif %>
                              <%= image_tag "gray.png" %>
                            <% end %>
                            </div>
                          <div class="recommended-book-detail">
                              <h6><%= link_to follower.name, user_path(follower) %></h6>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                    <% if @user.following %>
                      <% @user.following.each do |follower| %>
                        <div class="col-lg-3 col-xs-6 r-full-width masonry-grid following">
                          <div class="recommended-book">
                            <div class="recommended-book-img">
                            <% if follower.avatar.present? %>
                              <%= image_tag follower.avatar %>
                            <% elsif %>
                              <%= image_tag "gray.png" %>
                            <% end %>
                            </div>
                          <div class="recommended-book-detail">
                              <h6>
                                <% if follower.name.present? %>
                                  <%= link_to follower.name, user_path(follower) %>
                                <% else  %>
                                  <%= link_to follower.email.split("@").first,
                                    user_path(follower) %>
                                <% end %>
                              </h6>
                            </div>
                          </div>
                        </div>
                      <% end %>
                    <% end %>
                    </div>
                    </div>
                  </div>
              </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<script>
  $(".average-review-rating").raty({
    readOnly: true,
    path: "/assets/",
    score: function() {
      return $(this).attr("data-score")
    }
  });
</script>